development:
  adapter: postgresql
  encoding: unicode
  database: planner_dev
  pool: 5
  username: robert
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: planner_test
  pool: 5
  username: robert
  password:
